function timeData = importfile(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  TIMEDATA = IMPORTFILE1(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  TIMEDATA = IMPORTFILE1(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  timeData = importfile1("G:\Mój dysk\POSITION_TOY_9MO\SCRIPTS\Temporal-Analysis-Matlab\Time-Series-Analysis\Module_3_Burstiness\timeData.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 21-Aug-2024 18:59:52

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "index", "id", "inhand_right_child", "inhand_left_child", "mouthing", "Position"];
opts.SelectedVariableNames = ["index", "id", "inhand_right_child", "inhand_left_child", "mouthing", "Position"];
opts.VariableTypes = ["string", "double", "double", "string", "string", "string", "string"];

% Specify file level properties
opts.ImportErrorRule = "error";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "inhand_right_child", "inhand_left_child", "mouthing", "Position"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "inhand_right_child", "inhand_left_child", "mouthing", "Position"], "EmptyFieldRule", "auto");

% Import the data
timeData = readtable(filename, opts);

end